<a href="https://colab.research.google.com/github/althafnewdelhi/CE888_DataScience/blob/master/Lab_1/Lab1_Q%26A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab 1 - Questions to be done 
###1. Create a (4 x 2) integer array and print it's attributes


In [7]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


###2. Create an array of dimension (1,10) and sort it in ascending and descending order

In [11]:
y = np.array([[100,101,102,103,104,105,106,107,108,109,110]])
print(y.shape)
y.sort()
print("The ascending order is" +str(y))
print("The desending order is" +str(-np.sort(-y)))

(1, 11)
The ascending order is[[100 101 102 103 104 105 106 107 108 109 110]]
The desending order is[[110 109 108 107 106 105 104 103 102 101 100]]


###3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [12]:
x=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(x,(3,-1))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###4. Stack two arrays of any size horizontally and vertically

In [14]:
a = np.array([11,12,13,14,15])
b = np.array ([16,17,18,19,20])
x=np.hstack((a,b))
y=np.vstack((a,b))
print(x)
print(y)


[11 12 13 14 15 16 17 18 19 20]
[[11 12 13 14 15]
 [16 17 18 19 20]]


###5. Create two array of same size and find commom elements

In [15]:
array1=np.array([21,22,23,24,25])
print("Array1:",array1)
array2=np.array([31,22,33,34,25])
print("Array2:",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1,array2))

Array1: [21 22 23 24 25]
Array2: [31 22 33 34 25]
Common values between two arrays:
[22 25]


###6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [16]:
array1=np.random.random((5,5))
array1
print("Max:", array1.max())
print("Min:", array1.min())

Max: 0.9638692190052809
Min: 0.015116343712420433


###7. Create an array of size 100 and compute the mean, median, standard deviation.

In [21]:
array1= np.random.random((100))
array1
from statistics import median
print ("mean:", array1.mean())
print ("median:", median(array1))
print ("stddev:", array1.std())

mean: 0.4783237330681766
median: 0.47559049840949547
stddev: 0.2768613369504116


###8. Normalize a 5x5 random matrix

In [23]:
x=np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x=(x-xmin)/(xmax-xmin)
print("After normalisation:")
print(x)

Original Array:
[[0.82399651 0.62258553 0.7841213  0.34406276 0.60793345]
 [0.09116966 0.24330938 0.19616712 0.74281047 0.26954703]
 [0.94638699 0.10119688 0.18028206 0.98901721 0.08404013]
 [0.40184785 0.22958524 0.16252874 0.13841728 0.39786346]
 [0.46639788 0.47394448 0.56693094 0.18902659 0.01671253]]
After normalisation:
[[0.83027881 0.62313081 0.78926779 0.33667454 0.60806137]
 [0.07657798 0.23305128 0.1845662  0.74678026 0.26003629]
 [0.95615549 0.08689082 0.16822868 1.         0.06924537]
 [0.39610559 0.21893622 0.14996967 0.12517141 0.3920077 ]
 [0.46249427 0.47025583 0.56589094 0.17722229 0.        ]]


###9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [29]:
array1=np.random.random((4,4,3))
array2=np.random.random((4,4))
array1

array([[[0.64776728, 0.13368545, 0.91259795],
        [0.44647638, 0.70365292, 0.55355829],
        [0.81292618, 0.52065779, 0.52066172],
        [0.28756131, 0.45495716, 0.3395564 ]],

       [[0.14489972, 0.18790755, 0.10202127],
        [0.31524492, 0.85830577, 0.78555311],
        [0.13469731, 0.03611878, 0.09796417],
        [0.77593532, 0.41831695, 0.07962566]],

       [[0.38487952, 0.78100435, 0.65938905],
        [0.02321621, 0.0090163 , 0.68815346],
        [0.32753421, 0.62185301, 0.59872194],
        [0.54905489, 0.88999756, 0.96523484]],

       [[0.97719862, 0.53637145, 0.51566   ],
        [0.95006733, 0.22619203, 0.55063425],
        [0.18052053, 0.29022118, 0.68832618],
        [0.03051223, 0.36924399, 0.89761386]]])

In [30]:
array2

array([[0.44684098, 0.1551103 , 0.46154205, 0.6343817 ],
       [0.58481034, 0.6285787 , 0.72588551, 0.20969084],
       [0.20913667, 0.59259516, 0.22732486, 0.82261621],
       [0.63874116, 0.29892162, 0.05092529, 0.96848401]])

In [46]:
import numpy as np
array1= np.random.randint(1,10,(4,4,3))
array2= np.random.randint(1,10, (4,4))
print(array1*array2 [:,:,None])


[[[10  8 14]
  [24 18 30]
  [ 9  2  6]
  [ 9  6 24]]

 [[36 36 18]
  [ 8 56 16]
  [63 21 28]
  [45 81 81]]

 [[35 42 28]
  [ 8 14 10]
  [72  8 72]
  [18 54 54]]

 [[ 3  9  6]
  [63 14 35]
  [20 12 24]
  [21 21 56]]]
